name: storage_client
description: Dart client library to interact with Supabase Storage.
version: 1.0.0-dev.2
homepage: "https://supabase.io"
repository: "https://github.com/supabase/storage-dart"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4
  http_parser: ^4.0.1
  mime: ^1.0.2
  universal_io: ^2.0.4

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.21.4
  lints: ^2.0.0
