name: storage_client
description: Dart client library to interact with Supabase Storage.
version: 0.0.3
homepage: "https://supabase.io"
repository: "https://github.com/supabase/storage-dart"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0
  http_parser: ^4.0.0
  mime: ^1.0.0
  universal_io: ^2.0.4

dev_dependencies:
  lint: ^1.5.1
  mocktail: ^0.1.1
  test: ^1.16.4
